version: '3.0'

services:
  grafana:
    container_name: 'sameeraswal-odometer-panel'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3008:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/sameeraswal-odometer-panel
      - ./provisioning:/etc/grafana/provisioning
